-- Optional seed data for a fresh UNSW Co-op Society database.
-- Mirrors lib/placeholder-data.ts so a newly connected site looks the
-- same as the no-database preview. Replace with real content before launch.

insert into public.committee (name, role, degree, year, biography, linkedin_url, email, term, sort_order, photo_url) values
  ('Aisha Rahman', 'President', 'B. Commerce (Co-op)', '4th Year', 'Aisha leads the society''s strategic direction and represents Co-op scholars across UNSW and industry. She is passionate about building a community where every scholar feels at home.', 'https://www.linkedin.com/in/example', 'president@unswcoopsoc.com', '2026', 1, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&h=800&q=80'),
  ('Liam Chen', 'Vice President', 'B. Software Engineering (Co-op)', '3rd Year', 'Liam supports the executive team and oversees internal operations, making sure every portfolio has what it needs to deliver great experiences for members.', 'https://www.linkedin.com/in/example', null, '2026', 2, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&h=800&q=80'),
  ('Sofia Nguyen', 'Treasurer', 'B. Actuarial Studies (Co-op)', '2nd Year', 'Sofia manages the society''s finances and sponsorship budgets, keeping every event funded and every dollar accounted for.', 'https://www.linkedin.com/in/example', null, '2026', 3, 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&h=800&q=80'),
  ('James Patel', 'Secretary', 'B. Civil Engineering (Co-op)', '3rd Year', 'James keeps the society organised — minutes, records, and communications — so the committee can focus on serving members.', 'https://www.linkedin.com/in/example', null, '2026', 4, 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&h=800&q=80'),
  ('Emily Zhao', 'Events Director', 'B. Marketing (Co-op)', '2nd Year', 'Emily designs and delivers the society''s calendar of social and professional events, from first-year welcomes to industry networking nights.', 'https://www.linkedin.com/in/example', null, '2026', 5, 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=800&h=800&q=80'),
  ('Daniel Kim', 'Marketing Director', 'B. Computer Science (Co-op)', '3rd Year', 'Daniel runs the society''s brand and channels, keeping members informed and showcasing the Co-op community to the wider university.', 'https://www.linkedin.com/in/example', null, '2026', 6, 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=800&h=800&q=80');

insert into public.events (title, slug, description, agenda, category, starts_at, ends_at, venue, registration_url, is_published, banner_url) values
  ('Industry Networking Night 2026', 'industry-networking-night-2026', 'Our flagship networking evening connecting Co-op scholars with sponsor companies across banking, consulting, engineering, and technology. Meet graduate recruiters, hear from alumni, and build relationships that shape your career.', E'6:00 PM — Registration and welcome drinks\n6:30 PM — Opening address\n7:00 PM — Structured networking rotations\n8:30 PM — Canapés and open networking\n9:30 PM — Close', 'networking', '2026-08-14T08:00:00Z', '2026-08-14T11:30:00Z', 'Roundhouse, UNSW Kensington', 'https://events.humanitix.com/example', true, 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1600&h=900&q=80'),
  ('First Year Welcome BBQ', 'first-year-welcome-bbq', 'Kick off the year with the Co-op community! Meet your cohort, senior scholars, and the committee over a relaxed BBQ on the Village Green. All scholars welcome — food and drinks provided.', E'12:00 PM — BBQ opens\n12:30 PM — Welcome from the President\n1:00 PM — Games and mingling\n3:00 PM — Close', 'social', '2026-07-24T02:00:00Z', '2026-07-24T05:00:00Z', 'Village Green, UNSW Kensington', 'https://events.humanitix.com/example', true, 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1600&h=900&q=80'),
  ('Resume & Interview Workshop', 'resume-interview-workshop', 'A hands-on workshop with industry mentors covering resume writing, behavioural interviews, and assessment centres — tailored to Co-op placement applications.', E'5:00 PM — Resume clinic\n6:00 PM — Interview techniques panel\n7:00 PM — Mock interview practice\n8:00 PM — Close', 'professional', '2026-08-05T07:00:00Z', '2026-08-05T10:00:00Z', 'Colombo Theatre B, UNSW Kensington', 'https://events.humanitix.com/example', true, 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1600&h=900&q=80'),
  ('Charity Trivia Night', 'charity-trivia-night', 'An evening of trivia, prizes, and fundraising, with all proceeds supporting youth education charities. Bring a team of six or join one on the night.', E'6:30 PM — Doors open\n7:00 PM — Trivia rounds begin\n9:00 PM — Prizes and raffle\n9:30 PM — Close', 'charity', '2026-09-10T08:30:00Z', '2026-09-10T11:30:00Z', 'The Whitehouse, UNSW Kensington', 'https://events.humanitix.com/example', true, 'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=1600&h=900&q=80'),
  ('Exam Season Study Sessions', 'exam-season-study-sessions', 'Structured group study sessions across common Co-op courses, with senior scholars on hand to help. Coffee and snacks provided.', null, 'academic', '2026-11-02T23:00:00Z', '2026-11-03T07:00:00Z', 'Main Library, UNSW Kensington', null, true, 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1600&h=900&q=80'),
  ('End of Term Harbour Cruise', 'end-of-term-harbour-cruise', 'Celebrate the end of term with the Co-op community on Sydney Harbour. Dinner, music, and views — our most anticipated social event of the year.', null, 'social', '2026-04-17T08:00:00Z', '2026-04-17T12:00:00Z', 'King Street Wharf, Darling Harbour', null, true, 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1600&h=900&q=80');

insert into public.sponsors (name, slug, description, website_url, industry, partnership_info, tier, sort_order) values
  ('Macquarie Group', 'macquarie-group', 'A global financial services group providing banking, advisory, and asset management services, and a long-standing employer of UNSW Co-op scholars.', 'https://www.macquarie.com', 'Financial Services', 'Principal sponsor supporting our flagship networking events and professional development workshops.', 'principal', 1),
  ('Atlassian', 'atlassian', 'An Australian software company building collaboration tools used by teams worldwide, with strong graduate and Co-op placement pathways.', 'https://www.atlassian.com', 'Technology', 'Major sponsor hosting site visits and technical workshops for our members.', 'major', 2),
  ('Arup', 'arup', 'A global firm of designers, engineers, and consultants working across the built environment, offering placements to Co-op engineering scholars.', 'https://www.arup.com', 'Engineering & Consulting', 'Major sponsor supporting our engineering stream events and mentoring initiatives.', 'major', 3),
  ('KPMG Australia', 'kpmg-australia', 'A professional services firm providing audit, tax, and advisory services, partnering with the society on career development programs.', 'https://kpmg.com/au', 'Professional Services', 'Supporting sponsor contributing to our resume workshops and case competitions.', 'supporting', 4);

insert into public.news (title, slug, excerpt, body, published_at, is_published, cover_url) values
  ('2026 Committee Announced', '2026-committee-announced', 'Meet the scholars leading the society this year — a team spanning commerce, engineering, and computing cohorts.', 'We are excited to announce the 2026 committee. Following our AGM, six scholars were elected to lead the society this year. The new team brings experience across every Co-op stream and a shared vision: more events, deeper industry ties, and a stronger community for every scholar.', '2026-02-10T00:00:00Z', true, 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1600&h=900&q=80'),
  ('Record Turnout at O-Week Stall', 'record-turnout-o-week', 'Hundreds of new and returning students visited our O-Week stall to learn about the Co-op Program and society life.', 'This year''s O-Week was our biggest yet. Over three days, the committee met hundreds of prospective and current scholars, answered questions about the Co-op Program, and signed up a record number of new members. Thank you to everyone who stopped by — we can''t wait to see you at the Welcome BBQ.', '2026-02-20T00:00:00Z', true, 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1600&h=900&q=80'),
  ('New Sponsor Partnerships for 2026', 'new-sponsor-partnerships-2026', 'We''re welcoming new industry partners this year, expanding placement insights and networking opportunities for members.', 'The society is proud to welcome new sponsor partners for 2026. These partnerships fund our free member events and connect scholars directly with graduate recruiters and alumni mentors across finance, technology, and engineering.', '2026-03-05T00:00:00Z', true, 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1600&h=900&q=80');

insert into public.gallery (image_url, alt_text, category, width, height) values
  ('https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&h=800&q=80', 'Students celebrating at a society event', 'events', 1200, 800),
  ('https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&h=1200&q=80', 'Networking night at the Roundhouse', 'professional', 800, 1200),
  ('https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&h=800&q=80', 'Friends at the welcome BBQ on the Village Green', 'social', 1200, 800),
  ('https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&h=900&q=80', 'Speaker presenting at a professional workshop', 'professional', 1200, 900),
  ('https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=900&h=1200&q=80', 'Evening celebration on the harbour cruise', 'social', 900, 1200),
  ('https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1200&h=800&q=80', 'Volunteers at our charity fundraising event', 'community', 1200, 800),
  ('https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&h=800&q=80', 'Scholars studying together during exam season', 'events', 1200, 800),
  ('https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=1200&h=900&q=80', 'Team celebrating a trivia night win', 'community', 1200, 900);

insert into public.resources (title, description, category, file_url, external_url) values
  ('Co-op Scholar Resume Template', 'A clean, recruiter-approved resume template tailored to Co-op placement applications, with annotated examples.', 'resume', '/resources/coop-resume-template.pdf', null),
  ('Behavioural Interview Question Bank', 'Common behavioural questions asked in Co-op and graduate interviews, with STAR-method answer frameworks.', 'interview', '/resources/interview-question-bank.pdf', null),
  ('UNSW Co-op Program — Official Site', 'The official UNSW Co-op Program page: scholarship details, eligible degrees, and application dates.', 'scholarship', null, 'https://www.coop.unsw.edu.au'),
  ('First Placement Survival Guide', 'Advice from senior scholars on making the most of your first industry placement — expectations, etiquette, and growth.', 'career', '/resources/first-placement-guide.pdf', null),
  ('Scholarship Application Tips', 'How current scholars approached the Co-op application: personal statements, interviews, and assessment days.', 'scholarship', '/resources/scholarship-application-tips.pdf', null),
  ('LinkedIn Profile Checklist', 'A practical checklist for building a professional LinkedIn presence before recruitment season.', 'career', '/resources/linkedin-checklist.pdf', null);
